/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';
import { useLoader } from '@react-three/fiber';
import React, { Suspense } from 'react';

import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

export default function IONLogo({ ...props }: JSX.IntrinsicElements['group']) {
  const gltf = useLoader(GLTFLoader, '/assets/ion_logo_assets/ion_logo.gltf');

  return (
    <Suspense fallback={null}>
      <primitive
        {...props}
        // eslint-disable-next-line react/no-unknown-property
        object={gltf.scene}
        // eslint-disable-next-line react/no-unknown-property
        dispose={null}
        scale={
          window?.innerWidth <= 400 ? [0.05, 0.05, 0.05] : [0.08, 0.08, 0.08]
        }
      />
    </Suspense>
  );
}

useGLTF.preload('/assets/ion_logo_assets/ion_logo.gltf');
